##Challenge 1

In [1]:
'''select player, count(*) Total
from
(select player1 as player
from us_men_2013
union all
select player2 as player from us_men_2013
union all
select player1 as player from aus_men_2013
union all
select player2 as player from aus_men_2013
union all
select player1 as player from wimbledon_men_2013
union all
select player2 as player from wimbledon_men_2013
union all
select player1 as player from aus_men_2013
union all
select player2 as player from aus_men_2013
) d
group by player
order by total desc;'''



'''
         player         | total 
------------------------+-------
 Rafael Nadal           |    21
 Stanislas Wawrinka     |    18
 Roger Federer          |    16
 Tomas Berdych          |    16
 Novak Djokovic         |    16
 Andy Murray            |    15
 David Ferrer           |    15
 Tommy Robredo          |    13
 Richard Gasquet        |    12
 Grigor Dimitrov        |    11
 Florian Mayer          |    11
 Denis Istomin          |    10
 Stephane Robert        |    10
 Kevin Anderson         |    10
 Roberto Bautista Agut  |    10
 Milos Raonic           |    10
 Kei Nishikori          |     9
 Mikhail Youzhny        |     9
 Feliciano Lopez        |     9
 Fabio Fognini          |     9
'''


'''
select player, count(*) Total
from
(select player1 as player
from us_women_2013
union all
select player2 as player from us_women_2013
union all
select player1 as player from french_women_2013
union all
select player2 as player from french_women_2013
union all
select player1 as player from wimbledon_women_2013
union all
select player2 as player from wimbledon_women_2013
union all
select player1 as player from aus_ladies_2013
union all
select player2 as player from aus_ladies_2013
) d
group by player
order by total desc;
'''


'''
           player           | total 
----------------------------+-------
 Agnieszka Radwanska        |    17
 Dominika Cibulkova         |    16
 Na Li                      |    16
 Victoria Azarenka          |    16
 Serena Williams            |    15
 Maria Sharapova            |    15
 Ana Ivanovic               |    14
 Eugenie Bouchard           |    14
 Jelena Jankovic            |    13
 Angelique Kerber           |    12
 Sloane Stephens            |    12
 Simona Halep               |    11
 Flavia Pennetta            |    11
 Carla Suarez Navarro       |    10
 Garbine Muguruza           |    10
 Ekaterina Makarova         |     9
 Samantha Stosur            |     9
 Alize Cornet               |     9
 Jie Zheng                  |     9
 Elina Svitolina            |     8
 A.Radwanska                |     8
 Sara Errani                |     8
 Anastasia Pavlyuchenkova   |     8
'''

'\n           player           | total \n----------------------------+-------\n Agnieszka Radwanska        |    17\n Dominika Cibulkova         |    16\n Na Li                      |    16\n Victoria Azarenka          |    16\n Serena Williams            |    15\n Maria Sharapova            |    15\n Ana Ivanovic               |    14\n Eugenie Bouchard           |    14\n Jelena Jankovic            |    13\n Angelique Kerber           |    12\n Sloane Stephens            |    12\n Simona Halep               |    11\n Flavia Pennetta            |    11\n Carla Suarez Navarro       |    10\n Garbine Muguruza           |    10\n Ekaterina Makarova         |     9\n Samantha Stosur            |     9\n Alize Cornet               |     9\n Jie Zheng                  |     9\n Elina Svitolina            |     8\n A.Radwanska                |     8\n Sara Errani                |     8\n Anastasia Pavlyuchenkova   |     8\n'

##Challenge 2

In [2]:
print 'men: Rafa Nadal'
print 'women: Agnieszka Radwanska'

men: Rafa Nadal
women: Agnieszka Radwanska

##Challenge 3

In [4]:
'''
MAKE A NEW TABLE
create table men_majors as (select *
from us_men_2013
union all
select * from aus_men_2013
union all
select * from wimbledon_men_2013 union all
select * from french_men_2013)
;
'''

'''
MAKE NEW TABLE
create table women_majors as (select *
from us_women_2013
union all
select * from aus_ladies_2013
union all
select * from wimbledon_women_2013 union all
select * from french_women_2013)
;
'''

'''
select max(fsp_1), player1, max(fsp_2), player2 from men_majors
group by player1, player2
order by max(fsp_1) desc;
tennis=# select max(fsp_1), player1, max(fsp_2), player2 from men_majors
group by player1, player2
order by max(fsp_1) desc;
'''


'''
 max |        player1         | max |         player2         
-----+------------------------+-----+-------------------------
  85 | V.Hanescu              |  70 | R.Federer
  84 | Rafael Nadal           |  74 | Daniel Brands
  83 | Roberto Bautista Agut  |  55 | Gilles Muller
  82 | Julien Benneteau       |  65 | Roger Federer
  82 | Roberto Bautista Agut  |  61 | Tim Smyczek
  79 | Roberto Bautista Agut  |  64 | Jeremy Chardy
  79 | Pablo Andujar          |  67 | Jerzy Janowicz
  78 | Juan Monaco            |  52 | Daniel Gimeno-Traver
  78 | B.Tomic                |  64 | S.Querrey
  78 | Daniel Gimeno-Traver   |  56 | Viktor Troicki
  78 | Rafael Nadal           |  67 | Fabio Fognini
  78 | Rafael Nadal           |  60 | Stanislas Wawrinka
  78 | J.Monaco               |  58 | B.Knittel
  77 | Nikolay Davydenko      |  60 | Lukasz Kubot

'''

'''
select max(fsp_1), player1, max(fsp_2), player2 from men_majors
group by player1, player2
order by max(fsp_2) desc;
tennis=# select max(fsp_1), player1, max(fsp_2), player2 from men_majors
group by player1, player2
order by max(fsp_2) desc;
'''


'''
 max |        player1         | max |         player2         
-----+------------------------+-----+-------------------------
  52 | Roger Federer          |  84 | Carlos Berlocq
  56 | Adrian Ungur           |  84 | Gael Monfils
  66 | Ivo Karlovic           |  83 | Ivan Dodig
  58 | Benoit Paire           |  83 | Roberto Bautista Agut
  70 | John Isner             |  83 | Gael Monfils
  69 | R.Gasquet              |  81 | B.Tomic
  77 | T.Robredo              |  79 | A.Bogomolov Jr.
  63 | Tommy Haas             |  78 | John Isner
  54 | Martin Klizan          |  78 | John Isner
  63 | Simone Bolelli         |  77 | Yen-Hsun Lu
  52 | Marcos Baghdatis       |  77 | Denis Istomin
  68 | J.Monaco               |  77 | R.Ram
  54 | F.Lopez                |  76 | T.Haas
  62 | Blaz Kavcic            |  76 | Roger Federer
  57 | Benoit Paire           |  75 | Lukasz Kubot
  68 | D.Ferrer               |  74 | M.Alund

'''


'''
select max(fsp_1), player1, max(fsp_2), player2 from women_majors
group by player1, player2
order by max(fsp_2) desc;
'''


'''
 max |          player1           | max |          player2           
-----+----------------------------+-----+----------------------------
  58 | F Pennetta                 |  93 | S Errani
  67 | Carla Suarez Navarro       |  91 | Sara Errani
  46 | Sabine Lisicki             |  89 | Sara Errani
  57 | Francesca Schiavone        |  88 | Victoria Azarenka
  64 | Yulia Putintseva           |  87 | Sara Errani
  62 | Jelena Jankovic            |  86 | Kurumi Nara
  52 | Arantxa Rus                |  85 | Sara Errani
  55 | Barbora Zahlavova Strycova |  85 | Victoria Azarenka
  70 | Agnieszka Radwanska        |  84 | Sara Errani
  69 | Sandra Zahlavova           |  83 | Annika Beck
  63 | J.Larsson                  |  82 | E.Makarova
  47 | C Vandeweghe               |  82 | C Suarez Navarro
  80 | Shahar Peer                |  82 | Monica Niculescu
  54 | M Kirilenko                |  81 | S Halep
  52 | J Jankovic                 |  81 | K Nara
  71 | Barbora Zahlavova Strycova |  80 | Bojana Jovanovski

'''


'''
select max(fsp_1), player1, max(fsp_2), player2 from women_majors
group by player1, player2
order by max(fsp_1) desc;
'''



'''
 max |          player1           | max |          player2           
-----+----------------------------+-----+----------------------------
  86 | Anabel Medina Garrigues    |  53 | Irina Falconi
  85 | M.Niculescu                |  68 | M.Barthel
  82 | Monica Niculescu           |  64 | Johanna Larsson
  82 | Vania King                 |  75 | Sloane Stephens
  81 | Varvara Lepchenko          |  65 | Angelique Kerber
  81 | Jie Zheng                  |  57 | Maria Sharapova
  80 | Na Li                      |  64 | Ekaterina Makarova
  80 | K Nara                     |  58 | S Cirstea
  80 | Shahar Peer                |  82 | Monica Niculescu
  79 | K.Date-Krumm               |  79 | A.Cadantu
  79 | Carla Suarez Navarro       |  69 | Vania King
  79 | Kimiko Date-Krumm          |  59 | Samantha Stosur
  79 | L.Arruabarrena             |  60 | L.Tsurenko
  79 | S.Stephens                 |  56 | P.Cetkovska

'''

print "V.Hanescuhas best first serve %ge, with 85"
print "S Errani best first serve %ge, with 93"

V.Hanescuhas best first serve %ge, with 85
S Errani best first serve %ge, with 93

##Challenge 4

In [ ]:
'''
select player, unforced, total, 1.0*unforced/total as percentage
from
(select player1 as player, dbf_1 + ufe_1 as unforced, tpw_1 as total from men_majors
union all
select player2 as player, dbf_2 + ufe_2 as unforced, tpw_2 as total from men_majors
) d
where player = 'Rafael Nadal' or player = 'Stanislas Wawrinka' or player = 'Roger Federer'
;
'''

'''
       player       | unforced | total |       percentage       
--------------------+----------+-------+------------------------
 Roger Federer      |          |   103 |                       
 Stanislas Wawrinka |          |   103 |                       
 Roger Federer      |          |    94 |                       
 Stanislas Wawrinka |          |   111 |                       
 Roger Federer      |          |    90 |                       
 Stanislas Wawrinka |          |   151 |                       
 Roger Federer      |          |   101 |                       
 Stanislas Wawrinka |          |   127 |                       
 Stanislas Wawrinka |       12 |    54 | 0.22222222222222222222
 Rafael Nadal       |        6 |    30 | 0.20000000000000000000
 Stanislas Wawrinka |       50 |   142 | 0.35211267605633802817
 Rafael Nadal       |       20 |    91 | 0.21978021978021978022
 Rafael Nadal       |       18 |   107 | 0.16822429906542056075
 Stanislas Wawrinka |       40 |   118 | 0.33898305084745762712
 Rafael Nadal       |       29 |   129 | 0.22480620155038759690
 Stanislas Wawrinka |       65 |   153 | 0.42483660130718954248
 Rafael Nadal       |       54 |   147 | 0.36734693877551020408
 Rafael Nadal       |       26 |   105 | 0.24761904761904761905
 Rafael Nadal       |       35 |    88 | 0.39772727272727272727
 Stanislas Wawrinka |       53 |   146 | 0.36301369863013698630
 Rafael Nadal       |       30 |   140 | 0.21428571428571428571
 Stanislas Wawrinka |       39 |   111 | 0.35135135135135135135
 Rafael Nadal       |       31 |   113 | 0.27433628318584070796
 Stanislas Wawrinka |       31 |   136 | 0.22794117647058823529
 Rafael Nadal       |       41 |   122 | 0.33606557377049180328
 Stanislas Wawrinka |       61 |   191 | 0.31937172774869109948
 Rafael Nadal       |       25 |    91 | 0.27472527472527472527
 Rafael Nadal       |       17 |    96 | 0.17708333333333333333
 Rafael Nadal       |       27 |   100 | 0.27000000000000000000
 Rafael Nadal       |          |    94 |                       
 Rafael Nadal       |          |    84 |                       
 Rafael Nadal       |          |    90 |                       
 Rafael Nadal       |          |   136 |                       
 Rafael Nadal       |          |    82 |                       
 Stanislas Wawrinka |          |   107 |                       
 Stanislas Wawrinka |          |   165 |                       
 Rafael Nadal       |          |   102 |                       
 Rafael Nadal       |          |   121 |                       
 Roger Federer      |       22 |    96 | 0.22916666666666666667
 Roger Federer      |       22 |    96 | 0.22916666666666666667
 Roger Federer      |       35 |   103 | 0.33980582524271844660
 Roger Federer      |       19 |    98 | 0.19387755102040816327
 Roger Federer      |       22 |   100 | 0.22000000000000000000
 Roger Federer      |       42 |   147 | 0.28571428571428571429
 Stanislas Wawrinka |       53 |   143 | 0.37062937062937062937
 Roger Federer      |       51 |    86 | 0.59302325581395348837
 Stanislas Wawrinka |       51 |   116 | 0.43965517241379310345
 Roger Federer      |       19 |    88 | 0.21590909090909090909
 Roger Federer      |          |    88 |                       
 Roger Federer      |       21 |    98 | 0.21428571428571428571
 Roger Federer      |       58 |   147 | 0.39455782312925170068
 Roger Federer      |       37 |    73 | 0.50684931506849315068
 Stanislas Wawrinka |       44 |    64 | 0.68750000000000000000
 Rafael Nadal       |       47 |   177 | 0.26553672316384180791
 '''